version: '3.9'

services:

  java-app:
    container_name: java_app
    image: crud-java:1.0
    build: .
    ports:
      - 8080:8080
    depends_on:
      - java_db
  java_db:
    container_name: java_db
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mampi0712
      MYSQL_DATABASE: spring_maria
      MYSQL_USER: root1
      MYSQL_PASSWORD: root